name: Continuous Delivery

on:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Falha cedo se faltar algo no contexto
      - name: Assert Dockerfile & requirements
        run: |
          test -f Dockerfile && echo "Found Dockerfile" || (echo "No Dockerfile at root" && exit 1)
          test -f requirements.txt && echo "Found requirements.txt" || (echo "No requirements.txt at root" && exit 1)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # ex.: thiagocoelli (minúsculo)
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Access Token com Read & Write

      - name: Who am I
        run: docker info | grep Username || true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            thiagocoelli/minhaatividade:latest
            thiagocoelli/minhaatividade:sha-${{ github.sha }}
