name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install fastapi[standard]==0.116.1 pytest requests

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install fastapi[standard]==0.116.1 pytest requests

      - name: Run tests
        run: |
          pytest -q

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Assert Dockerfile & requirements
        run: |
          test -f Dockerfile && echo "Found Dockerfile" || (echo "No Dockerfile at root" && exit 1)
          test -f requirements.txt && echo "Found requirements.txt" || (echo "No requirements.txt at root" && exit 1)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ github.actor }}/minhaatividade:pr-${{ github.event.pull_request.number }}

  discord:
    needs: [ build, docker, testes ]
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Send Discord notification
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && env.DISCORD_WEBHOOK != '' }}
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ env.DISCORD_WEBHOOK }}
        with:
          args: |
              CI passou no PR #${{ github.event.pull_request.number }}
              Repo: ${{ github.repository }}
              Autor: ${{ github.actor }}
              Branch: ${{ github.head_ref }}
              Commit: ${{ github.sha }}
