name: Continuous Delivery

on:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Assert Dockerfile & requirements
        run: |
          ls -la
          test -f Dockerfile
          test -f requirements.txt
          sed -n '1,120p' Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: thiagocoelli
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Who am I
        run: docker info | grep Username || true


      - name: Push scope check (busybox)
        run: |
          docker pull busybox:latest
          docker tag busybox:latest thiagocoelli/pushcheck:tmp
          docker push thiagocoelli/pushcheck:tmp

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            thiagocoelli/minhaatividade:latest
            thiagocoelli/minhaatividade:sha-${{ github.sha }}
