name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Assert Dockerfile & requirements
        run: |
          test -f Dockerfile && echo "Found Dockerfile" || (echo "No Dockerfile at root" && exit 1)
          test -f requirements.txt && echo "Found requirements.txt" || (echo "No requirements.txt at root" && exit 1)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ github.actor }}/minhaatividade:pr-${{ github.event.pull_request.number }}

  discord:
    needs: [ lint, docker-build ]
    runs-on: ubuntu-latest

    if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository && secrets.DISCORD_WEBHOOK != '' }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Discord Webhook
        
        uses: johnnyhuy/actions-discord-git-webhook@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
